### PR TITLE
Use the correct magic number for encrypted txsets

### LINKED ISSUE #365: Unsigned txsets cannot be loaded via RPC
Commit 32d80ea5dd38bfb80f00f0d2fd0d3792dea7840e changed the version numbers in the txset magic headers back to their unencrypted values. This means that txsets exported by the RPC wallet are encrypted but have a magic number indicating that they are unencrypted, leading to the wallet failing to load them back in again. Instead the user just receives the response
```json
{"error": {"code": -39, "message": "cannot load unsigned_txset"}, "id": "1", "jsonrpc": "2.0"}
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #365

### CODE REVIEW

File: src/wallet/wallet2.cpp [hunk 1]
```diff
@@ -6317,6 +6323,11 @@ bool wallet2::parse_unsigned_tx_from_str(const std::string &unsigned_tx_st, unsi
       LOG_PRINT_L0("Failed to decrypt unsigned tx: " << e.what());
       return false;
     }
+    catch(...)
+    {
+    LOG_PRINT_L0("Failed to parse data from unsigned tx");
```
Comment (lxop) [inline src/wallet/wallet2.cpp]: This message should probably be "Failed to decrypt unsigned tx", shouldn't it?

File: src/wallet/wallet2.cpp [hunk 2]
```diff
@@ -6602,6 +6617,11 @@ bool wallet2::parse_tx_from_str(const std::string &signed_tx_st, std::vector<too
       LOG_PRINT_L0("Failed to decrypt signed transaction: " << e.what());
       return false;
     }
+    catch(...)
+    {
+    LOG_PRINT_L0("Failed to parse decrypted data from signed transaction");
```
Comment (lxop) [inline src/wallet/wallet2.cpp]: Likewise shouldn't this be "Failed to decrypt signed transaction"?

File: src/wallet/wallet2.cpp [hunk 3]
```diff
@@ -101,8 +101,9 @@ using namespace cryptonote;
 #define CHACHA8_KEY_TAIL 0x8c
 #define CACHE_KEY_TAIL 0x8d
 
-#define UNSIGNED_TX_PREFIX "Electroneum unsigned tx set"
-#define SIGNED_TX_PREFIX "Electroneum signed tx set"
+// Magic number 004 means these payloads are encrypted.
+#define UNSIGNED_TX_PREFIX "Electroneum unsigned tx set \004"
```
Comment (lxop) [inline src/wallet/wallet2.cpp]: There shouldn't be a space between "set" and the magic version number, otherwise new txsets will not be loadable by previous versions of the wallet

File: src/wallet/wallet2.cpp [hunk 4]
```diff
@@ -101,8 +101,9 @@ using namespace cryptonote;
...
+#define SIGNED_TX_PREFIX "Electroneum signed tx set \004"
```
Comment (lxop) [inline src/wallet/wallet2.cpp]: If you're putting the magic version number back into the constant prefix strings, you'll also need to put back the `- 1` on the calculations of `magiclen` on lines 6276 and 6570.

**Review by lxop — CHANGES_REQUESTED** [review]
A couple of bugs

**Comment by ghost** [comment]
Sorry was a quick run through yesterday. I read the code properly now and I see what's going on. Just replying to your points

File: src/wallet/wallet2.cpp (hunk 1 above)
Comment (ghost) [reply src/wallet/wallet2.cpp]: Yeah makes sense to have it the same as your new message.

File: src/wallet/wallet2.cpp (hunk 2 above)
Comment (ghost) [reply src/wallet/wallet2.cpp]: correct

File: src/wallet/wallet2.cpp (hunk 3 above)
Comment (ghost) [reply src/wallet/wallet2.cpp]: yes

File: src/wallet/wallet2.cpp (hunk 4 above)
Comment (ghost) [reply src/wallet/wallet2.cpp]: Yes that's right.

**Comment by ghost** [comment]
Ok @lxop does that look ok now? Will merge in on your word. Thanks.

File: src/wallet/wallet2.cpp [hunk 5]
```diff
@@ -6297,7 +6297,7 @@ bool wallet2::parse_unsigned_tx_from_str(const std::string &unsigned_tx_st, unsi
     }
     catch (...)
     {
-    LOG_PRINT_L0("Failed to parse data from unsigned tx");
+    LOG_PRINT_L0("Failed to parse decrypted data from unsigned tx");
```
Comment (lxop) [inline src/wallet/wallet2.cpp]: This one ought to remain "Failed to parse data from unsigned tx", but line 6622 ought to be "Failed to decrypt signed transaction"
